==26== Memcheck, a memory error detector
==26== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==26== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
==26== Command: python3.4 /usr/ichnosat/src/presentation/external_interface/start.py \> /usr/ichnosat/data_local/log/external_interface_pipe.log 2\> /usr/ichnosat/data_local/log/external_interface-err.log
==26== Parent PID: ==25== Cond==26== Invalid read of size 4
==26==    at 0x500546: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==    by 0x501C89: ??? (in /usr/bin/python3.4)
==26==  Address 0x623c020 is 1,056 bytes inside a block of size 3,892 free'd
==26==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==26==    by 0x534E7E: _PyBytes_Resize (in /usr/bin/python3.4)
==26==    by 0x534D6B: ??? (in /usr/bin/python3.4)
==26==    by 0x534ABD: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x50EC59: ??? (in /usr/bin/python3.4)
==26==    by 0x534E7E: _PyBytes_Resize (in /usr/bin/python3.4)
==26==    by 0x534D6B: ??? (in /usr/bin/python3.4)
==26==    by 0x534ABD: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==  Address 0x6241020 is 16 bytes inside a block of size 224 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x4D5575: ??? (in /usr/bin/python3.4)
==26==    by 0x4CEB77: PyDict_SetItem (in /usr/bin/python3.4)
==26==    by 0x504537: PyObject_SetAttr (in /usr/bin/python3.4)
==26==    by 0x4EE867: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4ED25F: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x500546: ??? (in /usr/bin/python3.4)
==26==    by 0x508691: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==26==  Address 0x625b020 is 32,288 bytes inside a block of size 35,476 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==26==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==26==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==  Address 0x625c020 is 736 bytes inside a block of size 911 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x508691: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x500546: ??? (in /usr/bin/python3.4)
==26==    by 0x508876: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==    by 0x4F3EE8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==  Address 0x6293020 is 1,296 bytes inside a block of size 3,696 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==26==    by 0x53758D: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==26==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==26==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==26==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==26==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==  Address 0x62c8020 is 6,944 bytes inside a block of size 8,470 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==26==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==26==    by 0x5086CD: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==  Address 0x6322020 is 16 bytes inside a block of size 368 free'd
==26==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==26==    by 0x4EB479: ??? (in /usr/bin/python3.4)
==26==    by 0x4E97C1: ??? (in /usr/bin/python3.4)
==26==    by 0x4E9997: ??? (in /usr/bin/python3.4)
==26==    by 0x4E9B3E: ??? (in /usr/bin/python3.4)
==26==    by 0x537524: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==26==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==26==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==  Address 0x6337020 is 7,056 bytes inside a block of size 9,814 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x4DD1D2: PyObject_GC_Del (in /usr/bin/python3.4)
==26==    by 0x508894: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==26==  Address 0x633a020 is 928 bytes inside a block of size 1,384 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==26==    by 0x53758D: ??? (in /usr/bin/python3.4)
==26==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==26==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==26==    by 0x508894: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==26==  Address 0x6357020 is 80 bytes inside a block of size 520 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==26==    by 0x4F924D: ??? (in /usr/bin/python3.4)
==26==    by 0x5086CD: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==26== 
==26== Invalid read of size 4
==26==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==26==    by 0x508894: ??? (in /usr/bin/python3.4)
==26==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==26==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==26==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==26==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==26==    by 0x509259: ??? (in /usr/bin/python3.4)
==26==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==26==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==26==  Address 0x62f5020 is 1,008 bytes inside a block of size 1,608 free'd
==26==    at 0x4C29E90: free (vg_replace_malloc.c:473)
: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25==  Address 0x633a020 is 176 bytes inside a block of size 224 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4E866A: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4ECA2A: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F281B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x508894: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==    by 0x5202A3: ??? (in /usr/bin/python3.4)
==25==    by 0x4FADF9: PyEval_CallObjectWithKeywords (in /usr/bin/python3.4)
==25==  Address 0x6357020 is 192 bytes inside a block of size 1,384 free'd
==25==    at 0x4C29E90: free (vg_replace_malloc.c:473)
==25==    by 0x4DAABC: ??? (in /usr/bin/python3.4)
==25==    by 0x53758D: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4EC9FB: PyEval_EvalCodeEx (in /usr/bin/python3.4)
==25==    by 0x4F25A8: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25== 
==25== Invalid read of size 4
==25==    at 0x4DD103: PyObject_GC_Del (in /usr/bin/python3.4)
==25==    by 0x508894: ??? (in /usr/bin/python3.4)
==25==    by 0x4F9206: ??? (in /usr/bin/python3.4)
==25==    by 0x5086AF: ??? (in /usr/bin/python3.4)
==25==    by 0x4FB0E7: ??? (in /usr/bin/python3.4)
==25==    by 0x4F1B8B: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x4F1B5E: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509259: ??? (in /usr/bin/python3.4)
==25==    by 0x5203E3: _PyObject_CallMethodIdObjArgs (in /usr/bin/python3.4)
==25==    by 0x51F0F8: PyImport_ImportModuleLevelObject (in /usr/bin/python3.4)
==25==  Address 0x6373020 is 32 bytes inside a block of size 40 free'd
==25==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==25==    by 0x4D8C26: ??? (in /usr/bin/python3.4)
==25==    by 0x54D58D: PyObject_CallObject (in /usr/bin/python3.4)
==25==    by 0x4D83D7: ??? (in /usr/bin/python3.4)
==25==    by 0x4CFF4D: PyType_Ready (in /usr/bin/python3.4)
==25==    by 0x4F7D54: ??? (in /usr/bin/python3.4)
==25==    by 0x548251: ??? (in /usr/bin/python3.4)
==25==    by 0x4EE019: PyEval_EvalFrameEx (in /usr/bin/python3.4)
==25==    by 0x509B6B: ??? (in /usr/bin/python3.4)
==25==    by 0x4F774D: PyObject_Call (in /usr/bin/python3.4)
==25==    by 0x547D1D: ??? (in /usr/bin/python3.4)
==25==    by 0x4F77E4: ??? (in /usr/bin/python3.4)
==25== 
